services:
  - type: web
    name: customer-categorizer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_DB_URL
        value: mongodb+srv://admin:Password123@cluster0.u35iao1.mongodb.net/?appName=Cluster0
      - key: MODEL_TRUSTED
        value: "1"
      - key: TRAINING_API_KEY
        value: testkey
      - key: PYTHON_VERSION
        value: 3.11.8

